import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Settings, ReportSummary, Transaction, XReport, ZReport } from '../api/client';

// ---------------------------------------------------------------------------
// Professional print documents, generated as real PDFs with jsPDF + autoTable
// (a proper PDF library) instead of hand-written HTML. The renderer builds the
// PDF and passes the bytes to the Electron main process, which prints them
// through a chrome-free window (see printing.ts / electron/main.js).
// ---------------------------------------------------------------------------

function money(amount: number | undefined, symbol: string): string {
  const n = Number(amount || 0);
  return `${symbol}${n.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function cap(value: string): string {
  const s = String(value || '');
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}

// Bill header shows only the sequence tail of INV-YYYYMMDD-NNN refs (e.g. 013).
function orderNumber(tx: Transaction): string {
  const m = String(tx.ref_number ?? '').match(/(\d+)\s*$/);
  return m ? m[1].slice(-3).padStart(3, '0') : String(tx.id ?? '');
}

function fmtDate(iso?: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return String(iso);
  return d.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

const MARGIN = 40;

type Section = {
  title: string;
  head: string[][];
  body: string[][];
  startY: number;
  align?: Record<number, 'left' | 'right' | 'center'>;
  emptyText?: string;
};

function drawHeader(doc: jsPDF, settings: Settings | null, title: string, subtitle: string): number {
  const s = settings || ({} as Settings);
  const store = s.store || 'Store POS';
  const pageW = doc.internal.pageSize.getWidth();
  const meta = [s.address_one, s.address_two, s.contact, s.tax ? `Tax ID: ${s.tax}` : '']
    .filter(Boolean)
    .join('    ·    ');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(20);
  doc.text(store, pageW / 2, 50, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(90);
  if (meta) doc.text(meta, pageW / 2, 66, { align: 'center', maxWidth: pageW - 2 * MARGIN });

  doc.setTextColor(20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(title.toUpperCase(), pageW / 2, 96, { align: 'center' });

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(90);
    doc.text(subtitle, pageW / 2, 112, { align: 'center' });
  }
  doc.setTextColor(20);
  return 132;
}

function drawSection(doc: jsPDF, section: Section): number {
  const pageW = doc.internal.pageSize.getWidth();
  let y = section.startY + 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(20);
  doc.text(section.title.toUpperCase(), MARGIN, y);
  y += 8;

  if (!section.body.length) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(section.emptyText || 'No data in this range.', MARGIN, y + 6);
    return y + 18;
  }

  autoTable(doc, {
    startY: y,
    head: section.head,
    body: section.body,
    margin: { left: MARGIN, right: MARGIN },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      font: 'helvetica',
      textColor: 20,
      lineColor: [185, 185, 185],
      lineWidth: 0.5,
    },
    headStyles: { fillColor: [43, 43, 43], textColor: 255, fontStyle: 'bold', fontSize: 8.5 },
    alternateRowStyles: { fillColor: [244, 244, 244] },
    columnStyles: Object.fromEntries(
      Object.entries(section.align || {}).map(([k, v]) => [Number(k), { halign: v }])
    ),
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
}

function drawFooter(doc: jsPDF, settings: Settings | null): void {
  const s = settings || ({} as Settings);
  const store = s.store || 'Store POS';
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const text = s.footer || `Generated by ${store} POS`;

  doc.setDrawColor(185);
  doc.line(MARGIN, pageH - 44, pageW - MARGIN, pageH - 44);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(120);
  doc.text(text, pageW / 2, pageH - 32, { align: 'center' });
  doc.text(`Printed on ${new Date().toLocaleString()}`, pageW / 2, pageH - 20, { align: 'center' });
}

function newDoc(): jsPDF {
  return new jsPDF({ unit: 'pt', format: 'a4', compress: false });
}

export function buildSalesReportPdf(args: {
  settings: Settings | null;
  start?: string;
  end?: string;
  report: ReportSummary;
}): ArrayBuffer {
  const { settings, start, end, report } = args;
  const symbol = settings?.symbol || '';
  const s = report.summary;
  const doc = newDoc();

  const range = start && end ? `${fmtDate(start)}  –  ${fmtDate(end)}` : 'All dates';
  let y = drawHeader(doc, settings, 'Sales Report', `Period: ${range}`);

  y = drawSection(doc, {
    title: 'Summary',
    head: [['Total Sales', 'Orders', 'Items Sold', 'Tax', 'Discount']],
    body: [
      [
        money(s.totalSales, symbol),
        String(s.saleCount),
        String(s.itemsSold),
        money(s.tax, symbol),
        money(s.discount, symbol),
      ],
    ],
    startY: y,
  });

  y = drawSection(doc, {
    title: 'Totals',
    head: [['Metric', 'Value']],
    body: [
      ['Gross Sales (subtotal)', money(s.subtotal, symbol)],
      ['Discounts', `- ${money(s.discount, symbol)}`],
      ['Tax', money(s.tax, symbol)],
      ['Net Sales', money(s.totalSales, symbol)],
      ['Orders', String(s.saleCount)],
      ['Items Sold', String(s.itemsSold)],
    ],
    startY: y,
    align: { 1: 'right' },
  });

  y = drawSection(doc, {
    title: 'Totals by Category',
    head: [['Category', 'Items', 'Revenue', 'Share']],
    body: report.byCategory.map((c) => [
      c.category,
      String(c.count),
      money(c.revenue, symbol),
      `${(s.totalSales ? (c.revenue / s.totalSales) * 100 : 0).toFixed(1)}%`,
    ]),
    startY: y,
    align: { 1: 'right', 2: 'right', 3: 'right' },
    emptyText: 'No sales in this range.',
  });

  y = drawSection(doc, {
    title: 'Totals by Payment Method',
    head: [['Method', 'Payments', 'Amount']],
    body: report.byPaymentMethod.map((p) => [
      cap(p.method),
      String(p.count),
      money(p.amount, symbol),
    ]),
    startY: y,
    align: { 1: 'right', 2: 'right' },
    emptyText: 'No sales in this range.',
  });

  y = drawSection(doc, {
    title: 'Best Sellers',
    head: [['#', 'Item', 'Qty', 'Revenue']],
    body: report.bestSellers.map((b, i) => [
      String(i + 1),
      b.name,
      String(b.quantity),
      money(b.revenue, symbol),
    ]),
    startY: y,
    align: { 0: 'right', 2: 'right', 3: 'right' },
    emptyText: 'No sales in this range.',
  });

  drawFooter(doc, settings);
  return doc.output('arraybuffer');
}

export function buildShiftReportPdf(args: {
  settings: Settings | null;
  report: XReport | ZReport;
  shift?: {
    id?: number;
    userName?: string;
    till?: number;
    openedAt?: string;
    closedAt?: string;
    floatAmount?: number;
    countedCash?: number;
  };
  type: 'X' | 'Z';
}): ArrayBuffer {
  const { settings, report, shift, type } = args;
  const symbol = settings?.symbol || '';
  const isZ = type === 'Z';
  const doc = newDoc();

  const headRows: string[][] = [
    ['Shift', `#${shift?.id ?? '?'}`],
    ['Cashier', shift?.userName || '-'],
    ['Till', String(shift?.till ?? 1)],
    ['Opened', fmtDate(shift?.openedAt)],
  ];
  if (isZ) headRows.push(['Closed', fmtDate(shift?.closedAt)]);

  let y = drawHeader(doc, settings, `${type} Report`, `Shift #${shift?.id ?? '?'}`);

  y = drawSection(doc, {
    title: 'Shift Information',
    head: [['Field', 'Value']],
    body: headRows,
    startY: y,
    align: { 1: 'right' },
  });

  y = drawSection(doc, {
    title: 'Sales Summary',
    head: [['Metric', 'Value']],
    body: [
      ['Total Sales', money(report.totalSales, symbol)],
      ['Cash Sales', money(report.cashSales, symbol)],
      ['Card Sales', money(report.cardSales, symbol)],
      ['Mobile Sales', money(report.mobileSales, symbol)],
      ['Sales (orders)', String(report.saleCount)],
      ['Transactions', String(report.transactionCount)],
      ['Net Sales', money(report.totalSales, symbol)],
    ],
    startY: y,
    align: { 1: 'right' },
  });

  y = drawSection(doc, {
    title: 'Refunds',
    head: [['Metric', 'Value']],
    body: [
      ['Refund Count', String(report.refundCount)],
      ['Refund Total', money(report.refundTotal, symbol)],
    ],
    startY: y,
    align: { 1: 'right' },
  });

  if (isZ) {
    const z = report as ZReport;
    y = drawSection(doc, {
      title: 'Cash Reconciliation',
      head: [['Metric', 'Value']],
      body: [
        ['Float Amount', money(shift?.floatAmount ?? 0, symbol)],
        ['Expected Cash', money(z.expectedCash, symbol)],
        ['Counted Cash', money(z.actualCash, symbol)],
        ['Difference', money(z.difference, symbol)],
      ],
      startY: y,
      align: { 1: 'right' },
    });
  }

  drawFooter(doc, settings);
  return doc.output('arraybuffer');
}

export function buildInvoicePdf(args: { settings: Settings | null; tx: Transaction }): ArrayBuffer {
  const { settings, tx } = args;
  const symbol = settings?.symbol || '';
  const doc = newDoc();

  let y = drawHeader(doc, settings, 'Order', `Order #${orderNumber(tx)}`);

  const infoRows: string[][] = [
    ['Date', fmtDate(tx.date)],
    ['Customer', tx.customer_name || 'Walk-in Customer'],
    ['Cashier', tx.user || '-'],
    ['Fulfillment', cap(tx.fulfillment || 'takeaway')],
  ];
  if (tx.fulfillment === 'delivery') {
    if (tx.delivery_name) infoRows.push(['Delivery Name', tx.delivery_name]);
    if (tx.delivery_contact) infoRows.push(['Contact', tx.delivery_contact]);
    if (tx.delivery_address) infoRows.push(['Address', tx.delivery_address]);
  }

  y = drawSection(doc, {
    title: 'Order Details',
    head: [['Field', 'Value']],
    body: infoRows,
    startY: y,
    align: { 1: 'right' },
  });

  y = drawSection(doc, {
    title: 'Items',
    head: [['Item', 'Qty', 'Unit Price', 'Amount']],
    body: (tx.items || []).map((it) => [
      it.name,
      String(it.quantity),
      money(it.price, symbol),
      money((Number(it.price) || 0) * (Number(it.quantity) || 0), symbol),
    ]),
    startY: y,
    align: { 1: 'right', 2: 'right', 3: 'right' },
  });

  y = drawSection(doc, {
    title: 'Totals',
    head: [['Metric', 'Value']],
    body: [
      ['Subtotal', money(tx.subtotal, symbol)],
      ['Discount', `- ${money(tx.discount, symbol)}`],
      ['Tax', money(tx.tax, symbol)],
      ['Total', money(tx.total, symbol)],
      ['Amount Paid', money(tx.paid, symbol)],
      ['Change', money(tx.change, symbol)],
    ],
    startY: y,
    align: { 1: 'right' },
  });

  if (tx.payment_breakdown && tx.payment_breakdown.length) {
    drawSection(doc, {
      title: 'Payments',
      head: [['Method', 'Amount']],
      body: tx.payment_breakdown.map((p) => [cap(p.method), money(p.amount, symbol)]),
      startY: y,
      align: { 1: 'right' },
    });
  }

  drawFooter(doc, settings);
  return doc.output('arraybuffer');
}
